### ISSUE TITLE
Issue with "add-domain-admin.sh"

### ISSUE THREAD

**Issue by ebusmaximus** [jeekkd/iRedMail-scripts#4]
Hello, are the scripts compatible with iredmail 1.3.2 ?
I'm using the add-domain-admin.sh
After using the sql commands i can't log in with the account i tried to change to a domain admin.
The url shows https://domain/iredadmin/domains?msg=PERMISSION_DENIED

**Comment by jeekkd** [comment]
Hello, I apologise for the delay. I will take a look at this

**Comment by jeekkd** [comment]
I can replicate this by using both iRedAdmin and my script, however the issue seems to be with iRedAdmin. If you mark a user as a Domain Admin (not global) they receive this error logging in. However if you then add Global Admin permission they are able to login successfully.

While its not ideal to have more permission than necessary you can work around this for now by making the user Global Admin:

`sh new-domain-admin.sh user@example.com ALL`
